package nhom2;


import java.util.Calendar;


public class PersonGod extends javax.swing.JFrame {

    class Clock implements Runnable {

        @Override
        public void run() {
            try {
                for (int i = 0; i < 5; i++) {
                    Calendar now = Calendar.getInstance();
                    int h = now.get(Calendar.HOUR);
                    int m = now.get(Calendar.MINUTE);
                    int s = now.get(Calendar.SECOND);
                    jTextArea1.append("Time: " + h + ":" + m + ":" + s + "\n");
                    Thread.sleep(1000);
                } 
            }
            catch (Exception e) {
                System.out.println(e);
            }
        }
        
    }
    
    class Dog implements Runnable {

        @Override
        public void run() {
            
                for (int i = 0; i < 5; i++) {
                    jTextArea1.append("Dog: Watching, Watching, Watching"+ "\n");
                    if (i == 4) {
                        jTextArea1.append("Dog : Go Go Go ..."+ "\n");
                    }
                    try{
                    Thread.sleep(500);
                    }catch (Exception e) {
                System.out.println(e);
            }
                
            }
            
        }
        
    }
    
    class Person implements Runnable {

        @Override
        public void run() {
            try {
                jTextArea1.append("Person: Wow, big Dog, run run run ... "+ "\n");
                for (int i = 10; i <= 50; i += 10) {
                    jTextArea1.append("Person: Run " + i + " so far."+ "\n");
                    if (i == 50) {
                        jTextArea1.append("Person: Safe. STOP"+ "\n");
                    }
                    Thread.sleep(1000);
                }
            
            } 
            catch (Exception e) {
                System.out.println(e);
            }
        }
        
    }
    Clock cl;
    Person ps;
    Dog dog;
    public PersonGod() {
        initComponents();
        cl = new Clock();
        ps = new Person();
        dog = new Dog();
        
                
    }
    private void running(){
         Thread clT = new Thread(cl);
        Thread psT = new Thread(ps);
        Thread dogT = new Thread(dog);
            clT.start();
            dogT.start();
            psT.start();
            try{
                dogT.join();
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        running();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonGod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
